extends: airbnb

env: 
  browser: true
  jest: true

parser: babel-eslint

rules:
  import/no-named-as-default-member: 0
  import/no-named-as-default: 0
  react/jsx-filename-extension: [1, {extensions: [".js", ".jsx"]}]